// Generated by gencpp from file servo_array_driver/Servo.msg
// DO NOT EDIT!


#ifndef SERVO_ARRAY_DRIVER_MESSAGE_SERVO_H
#define SERVO_ARRAY_DRIVER_MESSAGE_SERVO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servo_array_driver
{
template <class ContainerAllocator>
struct Servo_
{
  typedef Servo_<ContainerAllocator> Type;

  Servo_()
    : servo(0)
    , value(0.0)  {
    }
  Servo_(const ContainerAllocator& _alloc)
    : servo(0)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _servo_type;
  _servo_type servo;

   typedef float _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::servo_array_driver::Servo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo_array_driver::Servo_<ContainerAllocator> const> ConstPtr;

}; // struct Servo_

typedef ::servo_array_driver::Servo_<std::allocator<void> > Servo;

typedef boost::shared_ptr< ::servo_array_driver::Servo > ServoPtr;
typedef boost::shared_ptr< ::servo_array_driver::Servo const> ServoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servo_array_driver::Servo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servo_array_driver::Servo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::servo_array_driver::Servo_<ContainerAllocator1> & lhs, const ::servo_array_driver::Servo_<ContainerAllocator2> & rhs)
{
  return lhs.servo == rhs.servo &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::servo_array_driver::Servo_<ContainerAllocator1> & lhs, const ::servo_array_driver::Servo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace servo_array_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::servo_array_driver::Servo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_array_driver::Servo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_array_driver::Servo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_array_driver::Servo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_array_driver::Servo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_array_driver::Servo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servo_array_driver::Servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e89689ba58524f73da7d375fa49d8a1";
  }

  static const char* value(const ::servo_array_driver::Servo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e89689ba58524f7ULL;
  static const uint64_t static_value2 = 0x3da7d375fa49d8a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::servo_array_driver::Servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servo_array_driver/Servo";
  }

  static const char* value(const ::servo_array_driver::Servo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servo_array_driver::Servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# the Servo message is commonly used message in this package to\n"
"# assign a value to a specific servo. the purpose of the value is\n"
"# dependent on the topic or service being called\n"
"\n"
"int16 servo\n"
"float32 value\n"
;
  }

  static const char* value(const ::servo_array_driver::Servo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servo_array_driver::Servo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servo);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Servo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo_array_driver::Servo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servo_array_driver::Servo_<ContainerAllocator>& v)
  {
    s << indent << "servo: ";
    Printer<int16_t>::stream(s, indent + "  ", v.servo);
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVO_ARRAY_DRIVER_MESSAGE_SERVO_H
